//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYonetim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ProjeYonetimEntities : DbContext
    {
        public DB_ProjeYonetimEntities()
            : base("name=DB_ProjeYonetimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_EkDosya> tbl_EkDosya { get; set; }
        public virtual DbSet<tbl_Etiket> tbl_Etiket { get; set; }
        public virtual DbSet<tbl_Gorev> tbl_Gorev { get; set; }
        public virtual DbSet<tbl_GorevKullanici> tbl_GorevKullanici { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_KullaniciTur> tbl_KullaniciTur { get; set; }
        public virtual DbSet<tbl_Liste> tbl_Liste { get; set; }
        public virtual DbSet<tbl_Proje> tbl_Proje { get; set; }
        public virtual DbSet<tbl_ProjeDurumTur> tbl_ProjeDurumTur { get; set; }
        public virtual DbSet<tbl_ProjeKullanici> tbl_ProjeKullanici { get; set; }
    }
}
