//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjeKullanici
    {
        public int id_ProjeKullanici { get; set; }
        public int id_Proje { get; set; }
        public int id_Kullanici { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        public virtual tbl_Proje tbl_Proje { get; set; }
    }
}
