//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Proje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Proje()
        {
            this.tbl_Liste = new HashSet<tbl_Liste>();
            this.tbl_ProjeKullanici = new HashSet<tbl_ProjeKullanici>();
        }
    
        public int id_Proje { get; set; }
        public byte id_ProjeDurumTur { get; set; }
        public string ProjeAd { get; set; }
        public string Aciklama { get; set; }
        public string ProjeResim { get; set; }
        public int id_Kullanici { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Liste> tbl_Liste { get; set; }
        public virtual tbl_ProjeDurumTur tbl_ProjeDurumTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjeKullanici> tbl_ProjeKullanici { get; set; }
    }
}
